# Generated by Django 5.2.14 on 2026-05-21 13:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Module",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("position", models.PositiveIntegerField(default=0)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="modules",
                        to="catalog.course",
                    ),
                ),
            ],
            options={
                "ordering": ["position", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="Lesson",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(blank=True, max_length=220)),
                ("position", models.PositiveIntegerField(default=0)),
                (
                    "is_preview",
                    models.BooleanField(
                        default=False, help_text="Viewable without enrolling."
                    ),
                ),
                (
                    "module",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lessons",
                        to="content.module",
                    ),
                ),
            ],
            options={
                "ordering": ["position", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="ContentItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("text", "Rich text"),
                            ("video", "Video"),
                            ("file", "File / download"),
                            ("embed", "Embed"),
                        ],
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=200)),
                ("position", models.PositiveIntegerField(default=0)),
                (
                    "body",
                    models.TextField(
                        blank=True, help_text="Markdown for text content."
                    ),
                ),
                (
                    "media",
                    models.FileField(blank=True, null=True, upload_to="lesson_media/"),
                ),
                (
                    "url",
                    models.URLField(
                        blank=True, help_text="Embed or external media URL."
                    ),
                ),
                (
                    "lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="content.lesson",
                    ),
                ),
            ],
            options={
                "ordering": ["position", "created_at"],
                "indexes": [
                    models.Index(
                        fields=["lesson", "position"],
                        name="content_con_lesson__3265ba_idx",
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="module",
            index=models.Index(
                fields=["course", "position"], name="content_mod_course__4a5f60_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="lesson",
            index=models.Index(
                fields=["module", "position"], name="content_les_module__91a648_idx"
            ),
        ),
    ]
