# Generated by Django 5.2.14 on 2026-05-21 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="progression_mode",
            field=models.CharField(
                choices=[
                    ("open", "Open — any lesson, any order"),
                    ("sequential", "Sequential — unlock as you complete"),
                ],
                default="sequential",
                max_length=20,
            ),
        ),
    ]
